// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUUr0PWqNEcnjfUFLSBsjJce1Wygz5TU',
    appId: '1:541871011720:web:1c0af95bd94d1c2a46ac3d',
    messagingSenderId: '541871011720',
    projectId: 'e-tech-final',
    authDomain: 'e-tech-final.firebaseapp.com',
    storageBucket: 'e-tech-final.firebasestorage.app',
    measurementId: 'G-XCKXEQ5Y6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-JLd5vkwWEfmbMEOAj7Fo2rc2iJ2pNc',
    appId: '1:541871011720:android:c2f33d5555d8f53f46ac3d',
    messagingSenderId: '541871011720',
    projectId: 'e-tech-final',
    storageBucket: 'e-tech-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt22VDc2325RiFKB3aYILwPLdrOQbKZrk',
    appId: '1:541871011720:ios:1aa8f6bd0f8bc18b46ac3d',
    messagingSenderId: '541871011720',
    projectId: 'e-tech-final',
    storageBucket: 'e-tech-final.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt22VDc2325RiFKB3aYILwPLdrOQbKZrk',
    appId: '1:541871011720:ios:1aa8f6bd0f8bc18b46ac3d',
    messagingSenderId: '541871011720',
    projectId: 'e-tech-final',
    storageBucket: 'e-tech-final.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTUUr0PWqNEcnjfUFLSBsjJce1Wygz5TU',
    appId: '1:541871011720:web:093db03702cbf6b946ac3d',
    messagingSenderId: '541871011720',
    projectId: 'e-tech-final',
    authDomain: 'e-tech-final.firebaseapp.com',
    storageBucket: 'e-tech-final.firebasestorage.app',
    measurementId: 'G-QZ6Y320M6Y',
  );
}
